site_name: Jim
site_description: A JAX-based gravitational-wave inference toolkit
site_author: GW JAX Team
repo_url: https://github.com/GW-JAX-Team/jim
repo_name: GW-JAX-Team/jim

theme:
    name: material
    features:
        - navigation
        - toc
        - header.autohide
    palette:
        - scheme: slate
          primary: black
          accent: amber
          toggle:
             icon: material/brightness-5
             name: Light mode
        - scheme: default
          primary: blue
          accent: deep purple
          toggle:
             icon: material/brightness-2
             name: Dark mode

markdown_extensions:
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.snippets:
        base_path: docs
    - admonition
    - toc:
        permalink: "¤"
        toc_depth: 4

plugins:
    - search
    - autorefs
    - mkdocs-jupyter:
    - gen-files:
        scripts:
        - docs/gen_ref_pages.py
    - literate-nav:
        nav_file: SUMMARY.md
    - mkdocstrings:
        handlers:
            python:
                options:
                    docstring_style: google
                    inherited_members: true
                    show_root_heading: true
                    show_root_full_path: true
                    show_if_no_docstring: true
                    show_signature_annotations: true
                    show_source: false
                    members_order: source
                    heading_level: 4

nav:
    - Home: index.md
    - Getting Started: quickstart.md
    - Tutorials:
        - Anatomy of Jim: tutorials/anatomy_of_jim.md
        - Single Event PE: tutorials/single_event_PE.md
        - Gotchas: gotchas.md
    - Contributing: contributing.md
    - Changelog: changelog.md
    - API: api/
